url: https://www.amazon.com/dp/${asin}/
params:
  asin: B004GCJEZU
select:
  - name: name
    query: $('#title')
  - name: price
    query: $('#buybox .a-price .a-offscreen')
  - name: availability
    query: $('#availability')
